name: flutter_xoxo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.6.0
  http: ^1.2.2
  get_it: ^7.2.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.17
  build_runner: ^2.3.3
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.2.19

flutter_native_splash:
  color: "#32ff21" # Background color
  image: assets/background.jpg # Path to your logo/image
  android: true # Enable for Android
  ios: true # Enable for iOS

flutter:
  uses-material-design: true
  assets:
    - assets/background.jpg